name: mypy type checking

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash -l {0}

jobs:
  type_check:
    name: Type check with mypy on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - uses: mamba-org/setup-micromamba@617811f69075e3fd3ae68ca64220ad065877f246
        with:
          environment-name: myenv
          create-args: >-
            python=${{ matrix.python-version }}
            mypy
            matplotlib
            numpy

      - name: Install package
        run: pip install -e .

      - name: Run mypy on util.py
        run: python -m mypy src/stonerplots/util.py

      - name: Run mypy on base.py
        run: python -m mypy src/stonerplots/context/base.py

      - name: Run mypy on format.py
        run: python -m mypy src/stonerplots/format.py

      - name: Run mypy on counter.py
        run: python -m mypy src/stonerplots/counter.py

      - name: Run mypy on colours.py
        run: python -m mypy src/stonerplots/colours.py
